app:
  host: "127.0.0.1"
  port: 8025
  debug: false

paths:
  outputs: "../Resultados"
  cache_mdt: "cache/mdt"

datos:
  viario_gpkg: 'data\CalibradaBase.gpkg'
  capa_lineas: "V\u00edasDGT_Calibrada"
  capa_pks: "PK_2023"
  limites_gpkg: 'data\LimitesAdministrativos.gpkg'
  capa_ccaa: "CCAA"
  capa_provincias: "Provincias"

campos:
  carretera_lineas: ["ID_ROAD"]
  carretera_pks: ["MATRICULA"]
  sentido_lineas: ["SENTIDO", "Via_sentido", "via_sentido"]
  sentido_pks: ["SENTIDO"]
  m_inicio: ["m_from", "pk_inicio"]
  m_fin: ["m_to", "pk_fin"]
  pk_punto: ["VALORKM", "VALORM"]
  etiqueta_pk: ["LABEL", "PK+000", "VALORKM"]
  cota_pk: ["COORD_Z"]
  tipo_via: ["Tipo_via"]

crs:
  trabajo_epsg: 25830
  canarias_epsg: 4083
  geografico_epsg: 4326

mdt:
  wcs_url: "https://servicios.idee.es/wcs-inspire/mdt?VERSION=1.0.0"
  timeout_s: 45
  resoluciones_preferidas_m: [5, 25]
  max_pixeles: 4000000

mapas:
  margen_m_auto: 0.15
  margen_m_min: 250
  base: "ign_gris"

perfil:
  intervalo_muestreo_auto_m: 75
  suavizado_default: 4

pendientes:
  clases_base:
    - [-999, -8]
    - [-8, -6]
    - [-6, -4]
    - [-4, -2]
    - [-2, 2]
    - [2, 4]
    - [4, 6]
    - [6, 8]
    - [8, 999]
